export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const IS_LOADING = 'IS_LOADING'
export const CHARACTERS_PAGINATION = 'CHARACTERS_PAGINATION'