export const FETCH_CHARACTERS_BEGIN = 'FETCH_CHARACTERS_BEGIN'
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_CHARACTERS_FAILURE = 'FETCH_CHARACTERS_FAILURE'

export const FETCH_EXPLORE_BEGIN = 'FETCH_EXPLORE_BEGIN'
export const EXPLORE_PAGINATION = 'EXPLORE_PAGINATION'
export const FETCH_EXPLORE = 'FETCH_EXPLORE'
export const FETCH_EXPLORE_FAILURE = 'FETCH_EXPLORE_FAILURE'

export const FETCH_COMICS_BEGIN = 'FETCH_COMICS_BEGIN'
export const FETCH_COMICS = 'FETCH_COMICS'
export const FETCH_COMICS_FAILURE = 'FETCH_COMICS_FAILURE'

export const FETCH_SERIESES_BEGIN = 'FETCH_SERIESES_BEGIN'
export const FETCH_SERIESES = 'FETCH_SERIESES'
export const FETCH_SERIESES_FAILURE = 'FETCH_SERIESES_FAILURE'

export const FETCH_CHARACTER_BEGIN = 'FETCH_CHARACTER_BEGIN'
export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_CHARACTER_FAILURE = 'FETCH_CHARACTER_FAILURE'

export const FETCH_COMIC_BEGIN = 'FETCH_COMIC_BEGIN'
export const FETCH_COMIC = 'FETCH_COMIC'
export const FETCH_COMIC_FAILURE = 'FETCH_COMIC_FAILURE'

export const FETCH_SERIES_BEGIN = 'FETCH_SERIES_BEGIN'
export const FETCH_SERIES = 'FETCH_SERIES'
export const FETCH_SERIES_FAILURE = 'FETCH_SERIES_FAILURE'

export const FETCH_COMICS_BY_CHARACTER_BEGIN = 'FETCH_COMICS_BY_CHARACTER_BEGIN'
export const FETCH_COMICS_BY_CHARACTER = 'FETCH_COMICS_BY_CHARACTER_BEGIN'
export const FETCH_COMICS_BY_CHARACTER_FAILURE = 'FETCH_COMICS_BY_CHARACTER_FAILURE'

export const FETCH_SERIES_BY_CHARACTER_BEGIN = 'FETCH_SERIES_BY_CHARACTER_BEGIN'
export const FETCH_SERIES_BY_CHARACTER = 'FETCH_SERIES_BY_CHARACTER'
export const FETCH_SERIES_BY_CHARACTER_FAILURE = 'FETCH_SERIES_BY_CHARACTER_FAILURE'

export const IS_LOADING = 'IS_LOADING'
export const IS_OVERLAY = 'IS_OVERLAY'
export const FETCH_DETAIL = 'FETCH_DETAIL'
export const INFINITE_EXPLORE = 'INFINITE_EXPLORE'
